name: CI/CD Pipeline for React App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Set executable permissions for react-scripts
        run: chmod +x node_modules/.bin/react-scripts  # Устанавливаем права на выполнение для react-scripts

      - name: Build project
        run: npx --no-install react-scripts build  # Используем npx с флагом --no-install

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
