name: CI/CD Pipeline for React App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  Test-and-Deploy:
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          rm -f package-lock.json
          npm install
          npm ci
        env:
          CI: true

      - name: Run tests
        run: npm test
        env:
          CI: true

      - name: Build project
        run: CI=false npm run build

      - name: Save version
        id: version
        run: echo "tag=$(node -p -e "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            scotttish/artjobs:${{ steps.version.outputs.tag }}
            scotttish/artjobs:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Clean working directory
        run: git reset --hard && git clean -fd

      - name: Increase version
        run: npm version patch

      - name: Push new version
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/Scottttish/Artjobs.git main
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/Scottttish/Artjobs.git --tags
